rvm:
  - 2.2.9
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head

addons:
  firefox: latest

# whitelist
branches:
  only:
    - master

gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.2.9
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6_0.gemfile

before_install:
  - gem update --remote bundler
  - bin/install_geckodriver.sh
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt update && sudo apt install yarn

before_script: geckodriver -V
