---
name: build
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5.8', '2.6', '2.7', '3.0', '3.1' ]
        gemfile: [ 'rails_5_0', 'rails_5_1', 'rails_5_2', 'rails_6_0', 'rails_6_1', 'rails_7_0' ]
        exclude:
          # Newest ruby will test
          # - all permissible rails versions in latest major
          # - latest rails version in the last major
          # Supported rubies will test
          # - all permissible rails versions in latest major
          # - all permissible supported rails versions beneath latest major
          # Unsupported rubies will test
          # - all permissible rails versions released within 6 months of EOL

          # 2.5 -> Unsupported since March '21 -> Only test up to Sep '21
          # 2.6 -> Supported until March '22
          # 2.7 -> Supported until March '23 (At least)
          # 3.0 -> Supported for a while...
          - { ruby: '2.5.8', gemfile: 'rails_5_2' }
          - { ruby: '2.5.8', gemfile: 'rails_6_1' }
          - { ruby: '2.5.8', gemfile: 'rails_7_0' }
          - { ruby: '2.6', gemfile: 'rails_5_0' }
          - { ruby: '2.6', gemfile: 'rails_5_1' }
          - { ruby: '2.6', gemfile: 'rails_7_0' }
          - { ruby: '2.7', gemfile: 'rails_5_0' }
          - { ruby: '2.7', gemfile: 'rails_5_1' }
          - { ruby: '3.0', gemfile: 'rails_5_0' }
          - { ruby: '3.0', gemfile: 'rails_5_1' }
          - { ruby: '3.0', gemfile: 'rails_5_2' }
          - { ruby: '3.0', gemfile: 'rails_6_0' }
          - { ruby: '3.1', gemfile: 'rails_5_0' }
          - { ruby: '3.1', gemfile: 'rails_5_1' }
          - { ruby: '3.1', gemfile: 'rails_5_2' }
          - { ruby: '3.1', gemfile: 'rails_6_0' }
          - { ruby: '3.1', gemfile: 'rails_6_1' }
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: '2.1.4'
          bundler-cache: true
      - run: bundle exec rake spec
      - run: bundle exec rubocop
      # ruby-2.5.8 and 2.5.9 has issues running bundle install during specs.
      # see errors here https://github.com/mgrunberg/cucumber-rails/runs/4824503004?check_suite_focus=true
      # seems incompatibility with psych gem and rubygems version.
      - run: gem update --system
        if: matrix.ruby == '2.5.8'
      - run: bundle exec rake cucumber
